# Generated by Django 5.1.4 on 2025-12-27 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscamerava',
            name='hora',
            field=models.IntegerField(verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='dadoscamerava',
            name='minuto',
            field=models.IntegerField(verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='dadoscameravag20',
            name='hora',
            field=models.IntegerField(verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='dadoscameravag20',
            name='minuto',
            field=models.IntegerField(verbose_name='Nivel'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('operator_senior', 'Operador Senior'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Perfil')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Tentativas falhas')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Deve trocar senha')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Última troca de senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Falhou'), ('logout', 'Logout'), ('user_create', 'Criação de Usuário'), ('user_edit', 'Edição de Usuário'), ('user_delete', 'Exclusão de Usuário'), ('user_activate', 'Ativação de Usuário'), ('user_deactivate', 'Desativação de Usuário'), ('user_unlock', 'Desbloqueio de Usuário'), ('permission_grant', 'Concessão de Permissão'), ('permission_revoke', 'Revogação de Permissão'), ('password_change', 'Alteração de Senha'), ('password_reset', 'Reset de Senha'), ('settings_change', 'Alteração de Configuração'), ('camera_access', 'Acesso a Câmera'), ('export_data', 'Exportação de Dados'), ('report_generate', 'Geração de Relatório')], max_length=50, verbose_name='Ação')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Recurso')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Recurso')),
                ('details', models.JSONField(default=dict, verbose_name='Detalhes')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('users', 'Usuários'), ('cameras', 'Câmeras'), ('mosaic', 'Mosaico'), ('map', 'Mapa'), ('reports', 'Relatórios'), ('audit', 'Auditoria'), ('settings', 'Configurações')], max_length=50, verbose_name='Recurso')),
                ('action', models.CharField(choices=[('view', 'Visualizar'), ('view_all', 'Visualizar Todos'), ('view_assigned', 'Visualizar Atribuídos'), ('add', 'Adicionar'), ('edit', 'Editar'), ('delete', 'Excluir'), ('control', 'Controlar'), ('create', 'Criar'), ('edit_layers', 'Editar Camadas'), ('add_markers', 'Adicionar Marcadores'), ('export', 'Exportar'), ('generate', 'Gerar'), ('view_own', 'Ver Próprios')], max_length=50, verbose_name='Ação')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='Escopo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'db_table': 'user_permissions',
                'unique_together': {('user', 'resource', 'action')},
            },
        ),
    ]
