# Generated by Django 5.1.4 on 2025-12-27 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_user_management_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaResponsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('icone', models.CharField(default='fa-building', max_length=50)),
                ('cor', models.CharField(default='#B537F2', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agência Responsável',
                'verbose_name_plural': 'Agências Responsáveis',
                'db_table': 'agencias_responsaveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaOcorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(choices=[('fa-car-crash', 'Acidente de Trânsito'), ('fa-fire', 'Incêndio'), ('fa-tools', 'Infraestrutura'), ('fa-water', 'Emergência Ambiental'), ('fa-paw', 'Animal'), ('fa-exclamation-triangle', 'Evento Especial')], default='fa-exclamation-triangle', max_length=50)),
                ('cor', models.CharField(default='#00D4FF', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ocorrência',
                'verbose_name_plural': 'Categorias de Ocorrências',
                'db_table': 'categorias_ocorrencias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaGerenciada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_protocolo', models.CharField(editable=False, max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('origem', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('redes_sociais', 'Redes Sociais'), ('aplicativo', 'Aplicativo'), ('presencial', 'Presencial'), ('sistema', 'Sistema')], max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando', 'Aguardando Retorno'), ('resolvida', 'Resolvida'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=500)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(default='Rio de Janeiro', max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('solicitante_nome', models.CharField(blank=True, max_length=200)),
                ('solicitante_telefone', models.CharField(blank=True, max_length=20)),
                ('solicitante_email', models.EmailField(blank=True, max_length=254)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_gerenciadas_abertas', to=settings.AUTH_USER_MODEL)),
                ('agencias', models.ManyToManyField(blank=True, related_name='ocorrencias_gerenciadas', to='aplicativo.agenciaresponsavel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_gerenciadas', to='aplicativo.categoriaocorrencia')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_gerenciadas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência Gerenciada',
                'verbose_name_plural': 'Ocorrências Gerenciadas',
                'db_table': 'ocorrencias_gerenciadas',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOcorrenciaGerenciada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('mudanca_status', 'Mudança de Status'), ('atribuicao', 'Atribuição'), ('comentario', 'Comentário'), ('anexo', 'Anexo Adicionado')], max_length=20)),
                ('descricao', models.TextField()),
                ('dados_alterados', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='aplicativo.ocorrenciagerenciada')),
            ],
            options={
                'verbose_name': 'Histórico de Ocorrência',
                'verbose_name_plural': 'Históricos de Ocorrências',
                'db_table': 'historico_ocorrencias_gerenciadas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnexoOcorrenciaGerenciada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('outro', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to='ocorrencias/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('tamanho', models.IntegerField(help_text='Tamanho em bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='aplicativo.ocorrenciagerenciada')),
            ],
            options={
                'verbose_name': 'Anexo de Ocorrência',
                'verbose_name_plural': 'Anexos de Ocorrências',
                'db_table': 'anexos_ocorrencias_gerenciadas',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='pops/')),
                ('arquivo_path', models.CharField(blank=True, max_length=500)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('tempo_resposta_esperado', models.IntegerField(blank=True, help_text='Tempo esperado em minutos', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('versao', models.CharField(default='R00', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencias', models.ManyToManyField(blank=True, related_name='procedimentos', to='aplicativo.agenciaresponsavel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='aplicativo.categoriaocorrencia')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pops_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento Operacional',
                'verbose_name_plural': 'Procedimentos Operacionais',
                'db_table': 'procedimentos_operacionais',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='ocorrenciagerenciada',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='aplicativo.procedimentooperacional'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciagerenciada',
            index=models.Index(fields=['status', 'prioridade'], name='ocorrencias_status_ea9162_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciagerenciada',
            index=models.Index(fields=['categoria', 'data_abertura'], name='ocorrencias_categor_dedcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciagerenciada',
            index=models.Index(fields=['numero_protocolo'], name='ocorrencias_numero__27c901_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciagerenciada',
            index=models.Index(fields=['data_abertura'], name='ocorrencias_data_ab_17aedf_idx'),
        ),
    ]
