# Generated by Django 5.1.4 on 2025-12-28 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0003_ocorrencias_gerenciadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaOcorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('informada', 'Informada'), ('a_caminho', 'A Caminho'), ('presente', 'Presente no Local'), ('atuando', 'Em Atuação'), ('concluida', 'Concluída'), ('dispensada', 'Dispensada')], default='informada', max_length=20)),
                ('data_acionamento', models.DateTimeField(auto_now_add=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('acionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencias_acionadas', to=settings.AUTH_USER_MODEL)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acionamentos', to='aplicativo.agenciaresponsavel')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencias_acionadas', to='aplicativo.ocorrenciagerenciada')),
            ],
            options={
                'verbose_name': 'Agência Acionada',
                'verbose_name_plural': 'Agências Acionadas',
                'db_table': 'agencias_ocorrencias',
                'ordering': ['-data_acionamento'],
                'unique_together': {('ocorrencia', 'agencia')},
            },
        ),
    ]
