# Generated by Django 5.1.4 on 2025-12-28 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_agenciaocorrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizDecisoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_aprovacao', 'Em Aprovação'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20)),
                ('ativa', models.BooleanField(default=False)),
                ('peso_meteorologia', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('peso_incidentes', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('peso_mobilidade', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('peso_eventos', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('config_grupo1', models.JSONField(blank=True, default=dict)),
                ('config_grupo2', models.JSONField(blank=True, default=dict)),
                ('config_grupo3', models.JSONField(blank=True, default=dict)),
                ('config_grupo4', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matriz Decisória',
                'verbose_name_plural': 'Matrizes Decisórias',
                'db_table': 'matrizes_decisorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcaoRecomendada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_minimo', models.IntegerField()),
                ('nivel_maximo', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade_automatica', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('prazo_horas', models.IntegerField(blank=True, help_text='Prazo em horas para execução', null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('agencias', models.ManyToManyField(blank=True, related_name='acoes_matriz', to='aplicativo.agenciaresponsavel')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_matriz', to='aplicativo.categoriaocorrencia')),
                ('pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_matriz', to='aplicativo.procedimentooperacional')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='aplicativo.matrizdecisoria')),
            ],
            options={
                'verbose_name': 'Ação Recomendada',
                'verbose_name_plural': 'Ações Recomendadas',
                'db_table': 'acoes_recomendadas',
                'ordering': ['nivel_minimo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='EstagioOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_meteorologia', models.IntegerField(default=0)),
                ('nivel_incidentes', models.IntegerField(default=0)),
                ('nivel_mobilidade', models.IntegerField(default=0)),
                ('nivel_eventos', models.IntegerField(default=0)),
                ('nivel_cidade', models.IntegerField()),
                ('nivel_cidade_decimal', models.DecimalField(decimal_places=3, max_digits=5)),
                ('proximidade_proximo_nivel', models.DecimalField(decimal_places=4, max_digits=5)),
                ('dados_entrada', models.JSONField(default=dict)),
                ('detalhes_meteorologia', models.JSONField(blank=True, default=dict)),
                ('detalhes_incidentes', models.JSONField(blank=True, default=dict)),
                ('detalhes_mobilidade', models.JSONField(blank=True, default=dict)),
                ('detalhes_eventos', models.JSONField(blank=True, default=dict)),
                ('justificativa', models.TextField(blank=True)),
                ('acoes_geradas', models.JSONField(blank=True, default=list)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_solicitados', to=settings.AUTH_USER_MODEL)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos', to='aplicativo.matrizdecisoria')),
            ],
            options={
                'verbose_name': 'Estágio Operacional',
                'verbose_name_plural': 'Estágios Operacionais',
                'db_table': 'estagios_operacionais',
                'ordering': ['-calculado_em'],
                'indexes': [models.Index(fields=['-calculado_em', 'nivel_cidade'], name='estagios_op_calcula_cb9041_idx')],
            },
        ),
    ]
