# Generated by Django 5.1.4 on 2025-12-28 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0005_matrizdecisoria_acaorecomendada_estagiooperacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Prefeitura de Niterói', max_length=200)),
                ('slug', models.SlugField(help_text='Ex: niteroi', unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('responsavel_nome', models.CharField(blank=True, max_length=200)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=20)),
                ('config_apis', models.JSONField(blank=True, default=dict, help_text='Configurações de integração')),
                ('plano', models.CharField(choices=[('basico', 'Básico'), ('profissional', 'Profissional'), ('enterprise', 'Enterprise')], default='profissional', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_contratacao', models.DateField(auto_now_add=True)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clientes/logos/')),
                ('cores_personalizadas', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstacaoMeteorologica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_inmet', models.CharField(help_text='Código da estação (ex: A652)', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('automatica', 'Automática'), ('convencional', 'Convencional')], default='automatica', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=2, help_text='Metros', max_digits=7)),
                ('distancia_km', models.DecimalField(decimal_places=2, help_text='Distância em KM', max_digits=6)),
                ('principal', models.BooleanField(default=False, help_text='Estação principal para cálculos')),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='aplicativo.cliente')),
            ],
            options={
                'verbose_name': 'Estação Meteorológica',
                'verbose_name_plural': 'Estações Meteorológicas',
                'db_table': 'estacoes_meteorologicas',
                'ordering': ['cliente', 'distancia_km'],
            },
        ),
        migrations.CreateModel(
            name='DadosMeteorologicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True)),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('pressao', models.DecimalField(blank=True, decimal_places=2, help_text='hPa', max_digits=7, null=True)),
                ('precipitacao_horaria', models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=7, null=True)),
                ('precipitacao_diaria', models.DecimalField(blank=True, decimal_places=2, help_text='mm acumulado', max_digits=7, null=True)),
                ('vento_velocidade', models.DecimalField(blank=True, decimal_places=2, help_text='km/h', max_digits=6, null=True)),
                ('vento_direcao', models.DecimalField(blank=True, decimal_places=2, help_text='graus', max_digits=5, null=True)),
                ('vento_rajada', models.DecimalField(blank=True, decimal_places=2, help_text='km/h', max_digits=6, null=True)),
                ('radiacao', models.DecimalField(blank=True, decimal_places=2, help_text='kJ/m²', max_digits=7, null=True)),
                ('ponto_orvalho', models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True)),
                ('dados_raw', models.JSONField(blank=True, default=dict)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='aplicativo.estacaometeorologica')),
            ],
            options={
                'verbose_name': 'Dado Meteorológico',
                'verbose_name_plural': 'Dados Meteorológicos',
                'db_table': 'dados_meteorologicos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='estacaometeorologica',
            index=models.Index(fields=['cliente', 'principal'], name='estacoes_me_cliente_9ced07_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosmeteorologicos',
            index=models.Index(fields=['estacao', '-data_hora'], name='dados_meteo_estacao_6e2106_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosmeteorologicos',
            index=models.Index(fields=['-data_hora'], name='dados_meteo_data_ho_f602bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dadosmeteorologicos',
            unique_together={('estacao', 'data_hora')},
        ),
    ]
