# Generated by Django 5.1.4 on 2025-12-28 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_multi_tenant_inmet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMobilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('total_jams', models.IntegerField(default=0, help_text='Total de congestionamentos')),
                ('jams_severos', models.IntegerField(default=0, help_text='Level >= 4 (muito lento/parado)')),
                ('jams_moderados', models.IntegerField(default=0, help_text='Level 2-3 (lento/moderado)')),
                ('jams_leves', models.IntegerField(default=0, help_text='Level 0-1 (livre/lento)')),
                ('total_alerts', models.IntegerField(default=0, help_text='Total de alertas')),
                ('acidentes_maiores', models.IntegerField(default=0, help_text='ACCIDENT_MAJOR')),
                ('acidentes_menores', models.IntegerField(default=0, help_text='ACCIDENT_MINOR')),
                ('perigos', models.IntegerField(default=0, help_text='HAZARD_*')),
                ('total_irregularidades', models.IntegerField(default=0, help_text='Total de irregularidades')),
                ('vias_interditadas', models.IntegerField(default=0, help_text='ROAD_CLOSED')),
                ('obras', models.IntegerField(default=0, help_text='CONSTRUCTION')),
                ('velocidade_media_kmh', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidade média das vias monitoradas', max_digits=6, null=True)),
                ('atraso_medio_segundos', models.IntegerField(blank=True, help_text='Atraso médio vs fluxo livre', null=True)),
                ('extensao_total_congestionamentos_m', models.IntegerField(blank=True, help_text='Soma dos comprimentos de todos os congestionamentos', null=True)),
                ('dados_raw', models.JSONField(blank=True, default=dict)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_mobilidade', to='aplicativo.cliente')),
            ],
            options={
                'verbose_name': 'Dado de Mobilidade',
                'verbose_name_plural': 'Dados de Mobilidade',
                'db_table': 'dados_mobilidade',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['cliente', '-data_hora'], name='dados_mobil_cliente_ae7986_idx'), models.Index(fields=['-data_hora'], name='dados_mobil_data_ho_d385ef_idx')],
            },
        ),
    ]
