# Generated by Django 5.1.4 on 2025-12-28 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_mobilidade_waze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('cod_trecho', models.IntegerField(help_text='Código único do trecho de via', primary_key=True, serialize=False)),
                ('cod_logradouro', models.CharField(db_index=True, help_text='CL - Código do logradouro', max_length=10)),
                ('tipo_abreviado', models.CharField(help_text='R, Av, Etr, Trv, Pç, etc', max_length=10)),
                ('tipo_extenso', models.CharField(help_text='Rua, Avenida, Estrada, Travessa, Praça, etc', max_length=50)),
                ('nome_parcial', models.CharField(db_index=True, help_text='Ex: Visconde de Albuquerque', max_length=200)),
                ('nome_completo', models.CharField(db_index=True, help_text='Ex: Av. Visconde de Albuquerque', max_length=300)),
                ('nome_mapa', models.CharField(help_text='Nome para exibição em mapas', max_length=300)),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cod_bairro', models.IntegerField(blank=True, null=True)),
                ('hierarquia', models.CharField(blank=True, db_index=True, help_text='Local, Coletora, Arterial primária, Arterial secundária', max_length=50, null=True)),
                ('sentido_unico', models.CharField(blank=True, help_text='B=bidirecional, outros=unidirecional', max_length=5, null=True)),
                ('velocidade_regulamentada', models.IntegerField(blank=True, help_text='Velocidade máxima permitida em km/h', null=True)),
                ('tipo_trecho', models.CharField(blank=True, help_text='Normal, Túnel, Viaduto, etc', max_length=20, null=True)),
                ('num_par_inicio', models.IntegerField(blank=True, null=True)),
                ('num_par_fim', models.IntegerField(blank=True, null=True)),
                ('num_impar_inicio', models.IntegerField(blank=True, null=True)),
                ('num_impar_fim', models.IntegerField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True, help_text='Via ativa no sistema')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'db_table': 'logradouros',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['nome_completo'], name='logradouros_nome_co_714a52_idx'), models.Index(fields=['nome_parcial'], name='logradouros_nome_pa_91b1d9_idx'), models.Index(fields=['bairro', 'hierarquia'], name='logradouros_bairro_2211f4_idx'), models.Index(fields=['cod_logradouro'], name='logradouros_cod_log_03f267_idx'), models.Index(fields=['hierarquia'], name='logradouros_hierarq_6d2ae2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CongestionamentoVia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('via_nome_waze', models.CharField(help_text='Nome original retornado pelo Waze', max_length=300)),
                ('jam_level', models.IntegerField(default=0, help_text='Nível 0-5 (0=livre, 5=parado)')),
                ('velocidade_atual', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidade atual em km/h (Waze)', max_digits=6, null=True)),
                ('atraso_segundos', models.IntegerField(blank=True, help_text='Atraso em relação ao tempo normal', null=True)),
                ('extensao_metros', models.IntegerField(blank=True, help_text='Extensão do congestionamento em metros', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('match_score', models.FloatField(blank=True, help_text='Score do fuzzy match (0-100)', null=True)),
                ('match_metodo', models.CharField(blank=True, help_text='exato, fuzzy, parcial, nao_encontrado', max_length=50, null=True)),
                ('criticidade', models.CharField(choices=[('normal', 'Normal'), ('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa'), ('critica', 'Crítica')], db_index=True, default='normal', max_length=20)),
                ('percentual_abaixo_regulamentada', models.FloatField(blank=True, help_text='% abaixo da velocidade regulamentada', null=True)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestionamentos_via', to='aplicativo.cliente')),
                ('dados_mobilidade', models.ForeignKey(blank=True, help_text='Coleta de onde veio este dado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='congestionamentos', to='aplicativo.dadosmobilidade')),
                ('logradouro', models.ForeignKey(blank=True, help_text='Via oficial vinculada (se encontrada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congestionamentos', to='aplicativo.logradouro')),
            ],
            options={
                'verbose_name': 'Congestionamento por Via',
                'verbose_name_plural': 'Congestionamentos por Via',
                'db_table': 'congestionamentos_via',
                'ordering': ['-data_hora', '-criticidade'],
                'indexes': [models.Index(fields=['cliente', '-data_hora'], name='congestiona_cliente_e8a582_idx'), models.Index(fields=['logradouro', '-data_hora'], name='congestiona_logrado_caac82_idx'), models.Index(fields=['-data_hora', 'criticidade'], name='congestiona_data_ho_b36981_idx'), models.Index(fields=['via_nome_waze'], name='congestiona_via_nom_096f44_idx')],
            },
        ),
    ]
