# Generated by Django 5.1.4 on 2025-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0008_logradouros_congestionamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolasmunicipais',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='escolasmunicipais',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='escolasmunicipais',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
