# Generated by Django 5.1.4 on 2025-12-30 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0009_add_escolas_lat_long_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaObservacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Área')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#00D4FF', max_length=7, verbose_name='Cor no Mapa')),
                ('geojson', models.JSONField(verbose_name='Polígono GeoJSON')),
                ('tipo_desenho', models.CharField(choices=[('polygon', 'Polígono'), ('rectangle', 'Retângulo')], default='polygon', max_length=20)),
                ('ativa', models.BooleanField(default=True, verbose_name='Área Ativa')),
                ('alerta_habilitado', models.BooleanField(default=True, verbose_name='Alertas Habilitados')),
                ('evento_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Evento')),
                ('evento_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Início do Evento')),
                ('evento_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Evento')),
                ('plano_contingencia', models.TextField(blank=True, null=True, verbose_name='Plano de Contingência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_observacao', to='aplicativo.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área de Observação',
                'verbose_name_plural': 'Áreas de Observação',
                'db_table': 'areas_observacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlertaArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ocorrencia_grave', 'Ocorrência Grave'), ('jam_severo', 'Congestionamento Severo'), ('sirene_acionada', 'Sirene Acionada'), ('chuva_forte', 'Chuva Forte'), ('nivel_mudou', 'Nível Operacional Mudou')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('info', 'Informação'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='atencao', max_length=20)),
                ('lido', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='aplicativo.areaobservacao')),
            ],
            options={
                'verbose_name': 'Alerta de Área',
                'verbose_name_plural': 'Alertas de Áreas',
                'db_table': 'alertas_area',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='InventarioArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dados', models.JSONField()),
                ('nivel_operacional', models.IntegerField(choices=[(1, 'E1 - Normal'), (2, 'E2 - Mobilização'), (3, 'E3 - Atenção'), (4, 'E4 - Alerta'), (5, 'E5 - Crise')], default=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='aplicativo.areaobservacao')),
            ],
            options={
                'verbose_name': 'Inventário de Área',
                'verbose_name_plural': 'Inventários de Áreas',
                'db_table': 'inventarios_area',
                'ordering': ['-data_hora'],
            },
        ),
    ]
