# Generated by Django 5.1.4 on 2025-12-30 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0010_areas_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaUsuarioConfirmado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alerta_id', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(choices=[('confirmado', 'Confirmado (Ciente)'), ('dispensado', 'Dispensado')], default='confirmado', max_length=20)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes', to='aplicativo.areaobservacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_confirmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Confirmado pelo Usuário',
                'verbose_name_plural': 'Alertas Confirmados pelos Usuários',
                'db_table': 'alertas_usuario_confirmado',
                'ordering': ['-data_confirmacao'],
                'unique_together': {('usuario', 'alerta_id')},
            },
        ),
    ]
