# Generated by Django 5.1.4 on 2025-12-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0011_add_alerta_usuario_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaobservacao',
            name='arquivo_origem',
            field=models.CharField(blank=True, help_text='Nome do arquivo KML/KMZ original', max_length=255, null=True, verbose_name='Arquivo de Origem'),
        ),
        migrations.AddField(
            model_name='areaobservacao',
            name='grupo_importacao',
            field=models.CharField(blank=True, help_text='Identificador para agrupar áreas importadas juntas', max_length=100, null=True, verbose_name='Grupo de Importação'),
        ),
        migrations.AddField(
            model_name='areaobservacao',
            name='importada_de_kml',
            field=models.BooleanField(default=False, verbose_name='Importada de KML'),
        ),
        migrations.AddField(
            model_name='areaobservacao',
            name='temporaria',
            field=models.BooleanField(default=False, help_text='Áreas temporárias desaparecem após evento_fim', verbose_name='Área Temporária'),
        ),
        migrations.AlterField(
            model_name='areaobservacao',
            name='tipo_desenho',
            field=models.CharField(choices=[('polygon', 'Polígono'), ('rectangle', 'Retângulo'), ('polyline', 'Linha'), ('marker', 'Ponto')], default='polygon', max_length=20),
        ),
    ]
