# Generated by Django 5.1.4 on 2026-01-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0012_area_observacao_scheduling_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciagerenciada',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando', 'Aguardando Retorno'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='Edificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('escola', 'Escola'), ('hospital', 'Hospital'), ('predio_publico', 'Prédio Público'), ('predio_privado', 'Prédio Privado'), ('terminal', 'Terminal'), ('estacao', 'Estação'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola_municipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificacao_vinculada', to='aplicativo.escolasmunicipais')),
            ],
            options={
                'verbose_name': 'Edificação',
                'verbose_name_plural': 'Edificações',
                'db_table': 'edificacoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoEdificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('camera', 'Câmera'), ('sensor_nivel', 'Sensor de Nível'), ('sensor_temp', 'Sensor de Temperatura'), ('sensor_umidade', 'Sensor de Umidade'), ('catraca', 'Catraca'), ('controle_acesso', 'Controle de Acesso'), ('medidor_energia', 'Medidor de Energia'), ('medidor_agua', 'Medidor de Água'), ('automacao', 'Automação'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('url_rtsp', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL RTSP')),
                ('url_snapshot', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Snapshot')),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado')], default='offline', max_length=20)),
                ('ip_endereco', models.GenericIPAddressField(blank=True, null=True)),
                ('porta', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_leitura', models.DateTimeField(blank=True, null=True)),
                ('edificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='aplicativo.edificacao')),
            ],
            options={
                'verbose_name': 'Dispositivo de Edificação',
                'verbose_name_plural': 'Dispositivos de Edificações',
                'db_table': 'dispositivos_edificacao',
                'ordering': ['edificacao', 'tipo', 'nome'],
            },
        ),
    ]
