# Generated by Django 5.1.4 on 2026-01-04 03:01

from django.db import migrations, models


def convert_roles(apps, schema_editor):
    """Converte roles antigos para os novos"""
    UserProfile = apps.get_model('aplicativo', 'UserProfile')

    # Mapeamento de roles antigos para novos
    role_mapping = {
        'superadmin': 'administrador',
        'admin': 'coordenador',
        'operator_senior': 'operador',
        'operator': 'planejamento',
        'viewer': 'planejamento',
    }

    # Módulos padrão por perfil
    default_modules = {
        'administrador': ['dashboard', 'ocorrencias', 'eventos', 'areas', 'matriz', 'cameras', 'usuarios'],
        'coordenador': ['dashboard', 'ocorrencias', 'eventos', 'areas', 'matriz', 'cameras'],
        'operador': ['dashboard', 'ocorrencias', 'eventos', 'cameras'],
        'planejamento': ['dashboard', 'areas', 'matriz'],
    }

    for profile in UserProfile.objects.all():
        old_role = profile.role
        new_role = role_mapping.get(old_role, 'operador')
        profile.role = new_role
        profile.allowed_modules = default_modules.get(new_role, [])
        profile.save()


def reverse_roles(apps, schema_editor):
    """Reverte roles para os antigos"""
    UserProfile = apps.get_model('aplicativo', 'UserProfile')

    role_mapping = {
        'administrador': 'superadmin',
        'coordenador': 'admin',
        'operador': 'operator_senior',
        'planejamento': 'operator',
    }

    for profile in UserProfile.objects.all():
        old_role = profile.role
        new_role = role_mapping.get(old_role, 'viewer')
        profile.role = new_role
        profile.allowed_modules = []
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0013_alter_ocorrenciagerenciada_status_edificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos Permitidos'),
        ),
        # Primeiro converter os dados dos roles existentes
        migrations.RunPython(convert_roles, reverse_roles),
        # Depois alterar os campos
        migrations.AlterField(
            model_name='userpermission',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizar'), ('add', 'Adicionar'), ('edit', 'Editar'), ('delete', 'Excluir'), ('control', 'Controlar')], max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('ocorrencias', 'Ocorrências'), ('eventos', 'Eventos'), ('areas', 'Áreas'), ('matriz', 'Matriz'), ('cameras', 'Câmeras'), ('usuarios', 'Usuários')], max_length=50, verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordenador', 'Coordenador'), ('operador', 'Operador'), ('planejamento', 'Planejamento')], default='operador', max_length=20, verbose_name='Perfil'),
        ),
    ]
